In [17]:
import pandas as pd
import numpy as np

In [18]:
#Read in the certificate feature alexa dataset
alexa = pd.read_csv("certificate features.alexa.csv")


In [19]:
alexa.head()

domain  has_cert  longetivity  valid_cert  extended_validation  \
0     www.yahoo.com      True          180        True                False   
1  www.google.co.in      True           83        True                False   
2    www.reddit.com      True         1100        True                False   
3  world.taobao.com      True           74        True                False   
4  www.google.co.jp      True           83        True                False   

   cert_age  multi_mtn  globalsign nv-sa  google inc  gandi  ...  \
0        61       True                 0           0      0  ...   
1        11       True                 0           1      0  ...   
2       826       True                 0           0      0  ...   
3        61       True                 1           0      0  ...   
4        11       True                 0           1      0  ...   

   wponabudget.com  reviews-by.ml  sewaknepal.org  watchvslivestreamtv.club  \
0                0              0               0                         0   
1                0              0               0                         0   
2                0              0               0                         0   
3                0              0               0                         0   
4                0              0               0                         0   

   nehanaxane.ga  alexis-collins10.tk  laborindonesia.com  egdemo.info  \
0              0                    0                   0            0   
1              0                    0                   0            0   
2              0                    0                   0            0   
3              0                    0                   0            0   
4              0                    0                   0            0   

   theflatbellydrink.com  class  
0                      0  alexa  
1                      0  alexa  
2                      0  alexa  
3                      0  alexa  
4                      0  alexa  

[5 rows x 2208 columns]

In [20]:
#Read in the certificate feature alexa dataset
phish = pd.read_csv("certificate features.phish.csv")

In [21]:
phish.head()

domain  has_cert  longetivity  valid_cert  \
0             yusqa.com      True          365        True   
1   yonnaforexbureau.gm      True           90        True   
2    www.serveradmin.gq      True           57        True   
3    themasterslive.com      True           90        True   
4  edicionsdeponent.com      True           90        True   

   extended_validation  cert_age  multi_mtn  globalsign nv-sa  google inc  \
0                False       257      False                 0           0   
1                False        61      False                 0           0   
2                False         6       True                 0           0   
3                False         1      False                 0           0   
4                False         7      False                 0           0   

   gandi  ...  wponabudget.com  reviews-by.ml  sewaknepal.org  \
0      0  ...                0              0               0   
1      0  ...                0              0               0   
2      0  ...                0              0               0   
3      0  ...                0              0               0   
4      0  ...                0              0               0   

   watchvslivestreamtv.club  nehanaxane.ga  alexis-collins10.tk  \
0                         0              0                    0   
1                         0              0                    0   
2                         0              0                    0   
3                         0              0                    0   
4                         0              0                    0   

   laborindonesia.com  egdemo.info  theflatbellydrink.com  class  
0                   0            0                      0  phish  
1                   0            0                      0  phish  
2                   0            0                      0  phish  
3                   0            0                      0  phish  
4                   0            0                      0  phish  

[5 rows x 2208 columns]

In [22]:
#merge alexa and phish datasets
df = pd.concat([phish,alexa], axis=0, join='outer', ignore_index=False, keys=None,
          levels=None, names=None, verify_integrity=False, copy=True)

In [23]:
df.tail()

domain  has_cert  longetivity  valid_cert  \
7071   www.weihenstephaner.de      True         1095        True   
7072   www.overnightprints.at      True         1187        True   
7073       tierradegracia.net      True          191        True   
7074          fluffyaudio.com      True          365        True   
7075  semirxb.world.tmall.com      True          354        True   

      extended_validation  cert_age  multi_mtn  globalsign nv-sa  google inc  \
7071                False       566      False                 0           0   
7072                False       881      False                 0           0   
7073                False         0       True                 0           0   
7074                False       274      False                 0           0   
7075                False        19       True                 1           0   

      gandi  ...  wponabudget.com  reviews-by.ml  sewaknepal.org  \
7071      0  ...                0              0               0   
7072      0  ...                0              0               0   
7073      0  ...                0              0               0   
7074      0  ...                0              0               0   
7075      0  ...                0              0               0   

      watchvslivestreamtv.club  nehanaxane.ga  alexis-collins10.tk  \
7071                         0              0                    0   
7072                         0              0                    0   
7073                         0              0                    0   
7074                         0              0                    0   
7075                         0              0                    0   

      laborindonesia.com  egdemo.info  theflatbellydrink.com  class  
7071                   0            0                      0  alexa  
7072                   0            0                      0  alexa  
7073                   0            0                      0  alexa  
7074                   0            0                      0  alexa  
7075                   0            0                      0  alexa  

[5 rows x 2208 columns]

In [24]:
#define features and target feature
x = df.iloc[:,1:7]
y = df.loc[:,"class"]

In [25]:
x.head()

has_cert  longetivity  valid_cert  extended_validation  cert_age  multi_mtn
0      True          365        True                False       257      False
1      True           90        True                False        61      False
2      True           57        True                False         6       True
3      True           90        True                False         1      False
4      True           90        True                False         7      False

In [26]:
y.head()

0    phish
1    phish
2    phish
3    phish
4    phish
Name: class, dtype: object

In [27]:
#convert target class to booleans

ylist = list(y)

count = 0
for i in ylist:
    if i == 'phish':
        ylist[count] = True
    elif i == 'alexa':
        ylist[count] = False
    count+=1

yboolean = pd.DataFrame(ylist, columns = ['target'])
yboolean.head()

target
0    True
1    True
2    True
3    True
4    True

In [28]:
#create train and test dataframes
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y)

In [102]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score


# Instantiate dt
#dt = DecisionTreeClassifier(max_depth=3)
dt = DecisionTreeClassifier()

# Instantiate ada
#ada = AdaBoostClassifier(base_estimator=dt, learning_rate = 0.05, n_estimators = 200)
ada = AdaBoostClassifier(base_estimator=dt)

# Fit ada to the training set
ada.fit(x_train, y_train)

# Compute the probabilities of obtaining the positive class
y_pred_proba = ada.predict_proba(x_test)[:,1]
y_pred_Ada = ada.predict(x_test)

from sklearn.metrics import accuracy_score

#AdaBoost accuracy
print('Accuracy attained from ADABoost model:', accuracy_score(y_test,y_pred_Ada))

Accuracy attained from ADABoost model: 0.919047619047619


In [42]:

from sklearn.model_selection import GridSearchCV

'''This loops iterates through different decision tree max depths and performs a grid search on the
AdaBoost model for each max depth'''
list1 = []
for i in range(1, 10, 2):

    param_grid = {
     'n_estimators': [50, 100, 200],
     'learning_rate' : [0.01,0.05,0.1,0.3,1],
     }

    ada2 = AdaBoostClassifier(DecisionTreeClassifier(max_depth=i))
    ada_search = GridSearchCV(ada2, param_grid, cv=3, scoring = 'accuracy')
    ada_search.fit(x_train, y_train)
    list1.append([pd.DataFrame(ada_search.cv_results_),i])


In [44]:
#gridsearch and for loop results
ada_cv = pd.DataFrame()
for j in list1:
    j[0]['max_depth'] = j[1]
    ada_cv = pd.concat([j[0], ada_cv])
ada_cv = ada_cv[['param_learning_rate', 'param_n_estimators', 'params','max_depth', 'mean_test_score', 'rank_test_score']]
ada_cv.sort_values(by=['mean_test_score'], ascending = False).head()

param_learning_rate param_n_estimators  \
5                0.05                200   
3                0.05                 50   
4                0.05                100   
2                0.01                200   
1                0.01                100   

                                         params  max_depth  mean_test_score  \
5  {'learning_rate': 0.05, 'n_estimators': 200}          3         0.927508   
3   {'learning_rate': 0.05, 'n_estimators': 50}          5         0.927359   
4  {'learning_rate': 0.05, 'n_estimators': 100}          3         0.926020   
2  {'learning_rate': 0.01, 'n_estimators': 200}          5         0.925722   
1  {'learning_rate': 0.01, 'n_estimators': 100}          5         0.925573   

   rank_test_score  
5                1  
3                1  
4                2  
2                2  
1                3

In [104]:
#Run AdaBoost using the best parameters and output accuracy
dt_best = DecisionTreeClassifier(max_depth=3)
ada_best = AdaBoostClassifier(base_estimator=dt_best, n_estimators = 200, learning_rate= 0.05)

ada_best.fit(x_train, y_train)
y_pred_Ada_best = ada_best.predict(x_test)
print('Accuracy attained from best ADABoost model:', accuracy_score(y_test,y_pred_Ada_best))

Accuracy attained from best ADABoost model: 0.9202380952380952


In [52]:
from sklearn.ensemble import RandomForestClassifier

In [105]:
#Fit a basic random forest classifier to certification data
forest_phish = RandomForestClassifier()
forest_phish.fit(x_train,y_train)

y_pred_RF = forest_phish.predict(x_test)

#Evaluate test set accuracy
print('Accuracy attained from RF model:', accuracy_score(y_test,y_pred_RF))

Accuracy attained from RF model: 0.9172619047619047


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [58]:
#gridsearch on random forest paramaters n_estimators, max_features, max_depth, bootstrap
param_grid = [
    # try 12 (3×4) combinations of hyperparameters
    {'n_estimators': [3, 10, 30], 'max_features': [0.1, 0.3, 0.5, 0.8, 1.0], 'max_depth':[2,4,7,10, 15]}, 
    #{'n_estimators': [50, 70, 90], 'max_features': [8, 10, 12, 15]},
    # then try 6 (2×3) combinations with bootstrap set as False
    {'bootstrap': [False], 'n_estimators': [3, 10, 30], 'max_features': [0.1, 0.3, 0.5, 0.8, 1.0], 'max_depth':[2,4,7,10, 15]}]

forest_phish = RandomForestClassifier()
# train across 5 folds, that's a total of (12+6)*5=90 rounds of training 
grid_forest = GridSearchCV(forest_phish, param_grid, cv=3,
                           scoring='accuracy')
grid_forest.fit(x_train,y_train.values.ravel())

GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=Fa...
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid=

In [70]:
#Random forest best paramaters
tuned_forest = pd.DataFrame(grid_forest.cv_results_)[['param_max_depth','param_max_features', 'param_bootstrap','param_n_estimators','params', 'mean_test_score', 'rank_test_score']]
tuned_forest.sort_values(by='mean_test_score', ascending= False).head()

param_max_depth param_max_features param_bootstrap param_n_estimators  \
49               10                0.3             NaN                 10   
37                7                0.5             NaN                 10   
122              10                0.1           False                 30   
115               7                0.8           False                 10   
40                7                0.8             NaN                 10   

                                                params  mean_test_score  \
49   {'max_depth': 10, 'max_features': 0.3, 'n_esti...         0.928401   
37   {'max_depth': 7, 'max_features': 0.5, 'n_estim...         0.927359   
122  {'bootstrap': False, 'max_depth': 10, 'max_fea...         0.927062   
115  {'bootstrap': False, 'max_depth': 7, 'max_feat...         0.926615   
40   {'max_depth': 7, 'max_features': 0.8, 'n_estim...         0.926466   

     rank_test_score  
49                 1  
37                 2  
122                3  
115                4  
40                 5

In [107]:
#Random forest fit with best parameters on train set and predicted against test set
forest_phish = RandomForestClassifier(max_depth = 10, max_features = 0.3, n_estimators = 10)
forest_phish.fit(x_train,y_train)

y_pred_best_RF = forest_phish.predict(x_test)

#Evaluate test set accuracy
print('Accuracy attained from RF model:', accuracy_score(y_test,y_pred_best_RF))

Accuracy attained from RF model: 0.9202380952380952


In [108]:
#Fit a basic CART classifier to certification data
dt = DecisionTreeClassifier()


#Fit dt to the training set
dt.fit(x_train,y_train)

#Predict test set labels
y_pred_CART = dt.predict(x_test)

#Evaluate test set accuracy
print('Accuracy attained from CART model:', accuracy_score(y_test,y_pred_CART))

Accuracy attained from CART model: 0.9160714285714285


In [69]:
#run gridsearch on CART model for criterion, max_depth, and min_weight_fraction_leaf parameters
from sklearn.model_selection import GridSearchCV

# list1 = []

param_grid = {
 'criterion': ['gini', 'entropy'],
 'max_depth': [1,2,4,8],
 'min_weight_fraction_leaf' : [0, 0.005, 0.02, 0.05, 0.2, 0.5],
 }

dt2 = DecisionTreeClassifier()
dt2_search = GridSearchCV(dt2, param_grid, cv=3, scoring = 'accuracy')
dt2_search.fit(x_train, y_train)
# list1.append(pd.DataFrame(dt2_search.cv_results_))


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 4, 8],
                         

In [75]:
#Display best CART grid search parameters
dt2_cv = pd.DataFrame(dt2_search.cv_results_)
dt2_cv = dt2_cv[['param_criterion', 'param_max_depth', 'param_min_weight_fraction_leaf','params', 'mean_test_score', 'rank_test_score']]

dt2_cv.sort_values(by='mean_test_score', ascending = False).head()

param_criterion param_max_depth param_min_weight_fraction_leaf  \
42         entropy               8                              0   
18            gini               8                              0   
36         entropy               4                              0   
19            gini               8                          0.005   
37         entropy               4                          0.005   

                                               params  mean_test_score  \
42  {'criterion': 'entropy', 'max_depth': 8, 'min_...         0.923489   
18  {'criterion': 'gini', 'max_depth': 8, 'min_wei...         0.923340   
36  {'criterion': 'entropy', 'max_depth': 4, 'min_...         0.917535   
19  {'criterion': 'gini', 'max_depth': 8, 'min_wei...         0.916791   
37  {'criterion': 'entropy', 'max_depth': 4, 'min_...         0.916791   

    rank_test_score  
42                1  
18                2  
36                3  
19                4  
37                4

In [109]:
dt2_search.best_params_

{'criterion': 'entropy', 'max_depth': 8, 'min_weight_fraction_leaf': 0}

In [111]:

CART_best = DecisionTreeClassifier(criterion= 'entropy', max_depth= 8, min_weight_fraction_leaf= 0)
CART_best.fit(x_train, y_train)
#Predict test set labels
CART_best_pred = CART_best.predict(x_test)

#Evaluate test set accuracy
print('Accuracy attained from CART model:', accuracy_score(y_test,CART_best_pred))

Accuracy attained from CART model: 0.9202380952380952


In [114]:
#Fit a basic KNN classifier to certification data
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier()
classifier.fit(x_train,y_train)
KNN_base_pred = classifier.predict(x_test)

#Evaluate test set accuracy
print('Accuracy attained from KNN model:', accuracy_score(y_test,KNN_base_pred))

Accuracy attained from KNN model: 0.9178571428571428


In [92]:
# Applying Grid Search to find the best model and the best parameters for KNN
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_neighbors': [1,2,3,5,10,20,50,100,200,500],
    'weights': ['uniform','distance'],
    'metric' : ['euclidean','manhattan']}
grid_search_KNN = GridSearchCV(estimator=classifier, param_grid=param_grid, cv= 5, verbose=1, n_jobs =-1)
grid_search_KNN.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  88 tasks      | elapsed:    1.6s
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:    4.0s finished


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [1, 2, 3, 5, 10, 20, 50, 100, 200, 500],
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=1)

In [94]:
#Display best params for KNN
KNN_best = pd.DataFrame(grid_search_KNN.cv_results_)
KNN_best[['rank_test_score','mean_test_score', 'params','param_weights', 'param_metric', 'param_n_neighbors']].sort_values(by='mean_test_score', ascending = False).head()

rank_test_score  mean_test_score  \
9                 1         0.917535   
29                1         0.917535   
4                 3         0.917088   
31                3         0.917088   
11                5         0.916791   

                                               params param_weights  \
9   {'metric': 'euclidean', 'n_neighbors': 10, 'we...      distance   
29  {'metric': 'manhattan', 'n_neighbors': 10, 'we...      distance   
4   {'metric': 'euclidean', 'n_neighbors': 3, 'wei...       uniform   
31  {'metric': 'manhattan', 'n_neighbors': 20, 'we...      distance   
11  {'metric': 'euclidean', 'n_neighbors': 20, 'we...      distance   

   param_metric param_n_neighbors  
9     euclidean                10  
29    manhattan                10  
4     euclidean                 3  
31    manhattan                20  
11    euclidean                20

In [95]:
grid_search_KNN.best_score_

0.9175349806490026

In [112]:
grid_search_KNN.best_params_

{'metric': 'euclidean', 'n_neighbors': 10, 'weights': 'distance'}

In [101]:
KNN_best = KNeighborsClassifier(metric= 'euclidean', n_neighbors= 10, weights= 'distance')
KNN_best.fit(x_train, y_train)
KNN_best_pred = KNN_best.predict(x_test)
KNN_best_pred
print('Accuracy attained from best KNN model:', accuracy_score(y_test,KNN_best_pred))

Accuracy attained from best KNN model: 0.9160714285714285


In [129]:
classification_results = [['AdaBoost Base', accuracy_score(y_test,y_pred_Ada)],
                ['AdaBoost Tuned', accuracy_score(y_test,y_pred_Ada_best)],
                ['Random Forest Base', accuracy_score(y_test,y_pred_RF)],
                ['Random Forest Tuned', accuracy_score(y_test,y_pred_best_RF)],
                ['CART Base', accuracy_score(y_test,y_pred_CART)],
                ['CART Tuned', accuracy_score(y_test,CART_best_pred)],
                ['KNN Base', accuracy_score(y_test,KNN_base_pred)],
                ['KNN Tuned', accuracy_score(y_test,KNN_best_pred)]]


confusion_matrix_all = [['AdaBoost Base', confusion_matrix(y_test,y_pred_Ada)],
                ['AdaBoost Tuned', confusion_matrix(y_test,y_pred_Ada_best)],
                ['Random Forest Base', confusion_matrix(y_test,y_pred_RF)],
                ['Random Forest Tuned', confusion_matrix(y_test,y_pred_best_RF)],
                ['CART Base', confusion_matrix(y_test,y_pred_CART)],
                ['CART Tuned', confusion_matrix(y_test,CART_best_pred)],
                ['KNN Base', confusion_matrix(y_test,KNN_base_pred)],
                ['KNN Tuned', confusion_matrix(y_test,KNN_best_pred)]]

In [122]:
results = pd.DataFrame(classification_results, columns= ['Model','Accuracy']).sort_values(by='Accuracy', ascending=False)

In [123]:
results
#Note that not all tuned models performed better on the test set.  This is likely due to the models not
#showing significant improvment with tuning, and a different random seed in the base run resulting in
#better slightly better accuracy

Model  Accuracy
2   Random Forest Base  0.922024
1       AdaBoost Tuned  0.920238
3  Random Forest Tuned  0.920238
5           CART Tuned  0.920238
0        AdaBoost Base  0.919048
6             KNN Base  0.917857
4            CART Base  0.916071
7            KNN Tuned  0.916071

In [132]:
#Confusion matrix of all results
pd.DataFrame(confusion_matrix_all, columns= ['Model', 'Confusion Matrix'])

Model         Confusion Matrix
0        AdaBoost Base  [[1348, 68], [68, 196]]
1       AdaBoost Tuned  [[1368, 48], [86, 178]]
2   Random Forest Base  [[1356, 60], [71, 193]]
3  Random Forest Tuned  [[1356, 60], [74, 190]]
4            CART Base  [[1347, 69], [72, 192]]
5           CART Tuned  [[1354, 62], [72, 192]]
6             KNN Base  [[1348, 68], [70, 194]]
7            KNN Tuned  [[1351, 65], [76, 188]]

In [138]:
#Confusion matrix of all results
for i in confusion_matrix_all:
    print(i[0])
    print(i[1])

AdaBoost Base
[[1348   68]
 [  68  196]]
AdaBoost Tuned
[[1368   48]
 [  86  178]]
Random Forest Base
[[1356   60]
 [  71  193]]
Random Forest Tuned
[[1356   60]
 [  74  190]]
CART Base
[[1347   69]
 [  72  192]]
CART Tuned
[[1354   62]
 [  72  192]]
KNN Base
[[1348   68]
 [  70  194]]
KNN Tuned
[[1351   65]
 [  76  188]]
